CFLAGS=-O3 -ffast-math -mavx2
CC=cc

all: ring_Ssend ring_Ssend_grouped ring_Isend
ring_Ssend: ring_Ssend.c
ring_Ssend_grouped: ring_Ssend_grouped.c
ring_Isend: ring_Isend.c
clean: 
	rm -f ring_Ssend ring_Ssend_grouped ring_Isend
