#!/bin/bash -l
#SBATCH --job-name="ex3_job_2_OpenMP"
#SBATCH --account="uzh8"
#SBATCH --time=00:05:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=36
#SBATCH --partition=debug
#SBATCH --constraint=mc
#SBATCH --hint=nomultithread
#SBATCH --error=ex3_job_2_OpenMP_error.log
#SBATCH --output=ex3_job_2_OpenMP_output.log

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

srun ./cpi_omp

