#!/bin/bash -l
#SBATCH --job-name="ex4_job_1_cpi"
#SBATCH --account="uzh8"
#SBATCH --time=00:05:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=36
#SBATCH --cpus-per-task=1
#SBATCH --partition=debug
#SBATCH --constraint=mc
#SBATCH --hint=nomultithread
#SBATCH --output=ex4_job_1_cpi_output.log
#SBATCH --error=ex4_job_1_cpi_error.log

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

srun ./cpi
