#!/bin/bash -l
#SBATCH --job-name="sum_omp"
#SBATCH --account="uzg2"
#SBATCH --time=00:05:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=18
#SBATCH --partition=debug
#SBATCH --constraint=gpu
#SBATCH --hint=nomultithread
#SBATCH --output=sum_omp.log

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

srun /users/rwassink/hpc_esc_401_solutions/exercise_session_03/sum
